language: python
cache: pip
branches:
  only:
  - master
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev" # 3.6 development branch
install:
  - pip install -r requirements.txt
script:
  - python manage.py test