version: "3.4"
services:

  redis:
    image: redis:alpine

  predict-python-server:
    image: nirdizatiresearch/predict-python
    command: python3 manage.py runserver localhost:8000

  predict-python-scheduler:
    image: nirdizatiresearch/predict-python
    command: python3 manage.py rqscheduler localhost:8000

  predict-python-worker:
    image: nirdizatiresearch/predict-python
    command: python3 manage.py rqworker default

